name: esp_serial_flasher
description: Allows flashing an esp32 over serial
dependencies:
  packing:
    url: github.com/mikkeldamsgaard/pkg-binary-packing
    version: ^1.0.0
  slip:
    url: github.com/mikkeldamsgaard/pkg-slip
    version: ^1.0.1
